// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Gunakan DIRECT_URL (port 5432) jika tersedia untuk menghindari hang/macet pada pooler port 6543 saat db push
    url: env("DIRECT_URL") || env("DATABASE_URL"),
  },
});
